### Introduction - callbacks
Asynchronous actions: actions that we initiate now, but they finish later. For instance, one such function is the ``setTimeout`` function.

Suppose we have a function ``loadScript`` which takes ``src`` as an argument and loads script from there. (asynchronous callback)
```js
function loadScript(src){
   // creates a <script> tag and append it to the page
  // this causes the script with given src to start loading and run when complete
  let script = document.createElement('script');
  script.src = src;
  document.head.append(script);
}
```
It inserts into the document a new, dynamically created, tag ``<script src="…">`` with the given src. The browser automatically starts loading it and executes when complete.

We can use this function like this:
```js
// load and execute the script at the given path
loadScript('/my/script.js');
```

The script is executed “asynchronously” by browser, as it starts loading now, but runs later, when the function has already finished.

But what if we have some variables or functions that are intiated and would be used just after the script, using them would raise an error. In this case we can add a callback 
```js
function loadScript(src, callback) {
  let script = document.createElement('script');
  script.src = src;

  script.onload = () => callback(script);

  document.head.append(script);
}
// Now if we want to call new functions from the script, we should write that in the callback:
loadScript('/my/script.js', function() {
  // the callback runs after the script is loaded
  newFunction(); // so now it works
  //...
});
```

Whats happening above is we create a function that accepts callback. Now since we want somethings intiated inside with this callback invocation we call it inside the callback only. In the function 
the callback is called with the script which is created inside the function using the ``src``.


**How can we load two scripts sequentially: the first one, and then the second one after it?**

The natural solution would be to put the second ``loadScript`` call inside the callback, like this:
```js
loadScript('/my/script.js', function(script)) {

  alert(`Cool, the ${script.src} is loaded, let's load one more`);

  loadScript('/my/script2.js', function(script) {
    alert(`Cool, the second script is loaded`);

      loadScript('/my/script2.js', function(script) {
        alert(`Cool, the third script is loaded`);
  });

});
```
What happens above is the outermost loadscript is executed and as ``document.onload = () => callback(script)`` is there it will call the callback which contains the other loadscript and so on. Thus executing from the outermost to innner most loadscript. 

After the outer ``loadScript`` is complete, the callback initiates the inner one.

What if we want one more script…?
```js
loadScript('/my/script.js', function(script) {

  loadScript('/my/script2.js', function(script) {

    loadScript('/my/script3.js', function(script) {
      // ...continue after all scripts are loaded
    });

  });

});
```
This results in a callback hell. 

### Callback Hell 

suppose we have a function that multiplies a number by 2 every time it is called. 
```js
function multiplyBy2(num, callback){
  num = num * 2;
  if(isNaN(num)){
    callback(new Error('Not a number'), num)
  }
  callback(null, num);
}

multiplyBy2('string', (err, num) => {
  if(err){
    console.log(err)
    return 
  } else{ // will need to check on every callback 
        multiplyBy2(num, (num) => {
        multiplyBy2(num, (num) => {
            console.log(num)
        })
    })
  }
})

```

### Handling Errors
What if the script loading fails? Our callback should be able to react on that.

Here’s an improved version of ``loadScript`` that tracks loading errors:
```js
function loadScript(src, callback) {
  let script = document.createElement('script');
  script.src = src;

  script.onload = () => callback(null, script);
  script.onerror = () => callback(new Error(`Script load error for ${src}`));

  document.head.append(script);
}
```
We add ``null`` and ``script`` cause we know if it's successful than it will call the callback with error.

It calls ``callback(null, script)`` for successful load and ``callback(error)`` otherwise.

The usage:
```js
loadScript('/my/script.js', function(error, script) {
  if (error) {
    // handle error
  } else {
    // script loaded successfully
  }
});
```

The convention is:

- The first argument of the callback is reserved for an error if it occurs. Then ``callback(err)`` is called.
- The second argument (and the next ones if needed) are for the successful result. Then ``callback(null, result1, result2…)`` is called.
So the single callback function is used both for reporting errors and passing back results.